# Generated by Django 3.2.6 on 2021-08-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_cabains_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cabains',
            options={},
        ),
    ]
