# Generated by Django 3.2.6 on 2021-08-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_cabains_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabains',
            name='image',
            field=models.ImageField(null=True, upload_to='Imagenes', verbose_name='Fotografía'),
        ),
    ]
