# Generated by Django 3.2.6 on 2021-08-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_alter_cabains_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabains',
            name='image',
            field=models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografía'),
        ),
    ]
